### ISSUE TITLE
Community top navigation fix

### ISSUE THREAD

**Issue by markknol** [HaxeFoundation/haxe.org#437]
Minor change, but at the moment the dots on community.haxe.org are displayed as blocks, and bit misaligned. 
![image](https://user-images.githubusercontent.com/576184/109304056-f8f2d700-783b-11eb-81a2-194cf324c87a.png)

```css
.brand.sub::before {
    content: "..";
    position: absolute;
    margin-left: -33px;
    margin-top: -23px; /* << move bit more to middle */
    line-height: 0px;
    font: bold 40px "Open Sans", serif; /* << serif font has round dots */
    letter-spacing: 0px;
    color: #f25c19;
}
```
These two changes will make it look like this 
![image](https://user-images.githubusercontent.com/576184/109304036-eed0d880-783b-11eb-82b8-5c3ada67769d.png)

@ibilon I assigned you since I think you're the one that can do this, thanks!
